project:
  type: website

website:
  title: "Dependency Ratios in Washington State 2011-2021"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: data-prep.qmd
        text: Prepare
      - href: data-proc.qmd
        text: Process

format:
  html:
    theme: pulse
    css: styles.css
    toc: true

editor: visual

