---
title: "Dependency ratios in Washington State 2011-2021"
---

## Overview
Dependency ratios are important quantities that facilitate policy planning. They provide interested governmental and non-governmental entities insight into population dynamics for regions of interest. The insights gain can help planners to anticipate changing needs as age demographics within the population change. Given scarcity of resources, dependency ratios can inform where limited funds can best be applied to ensure that they are used effectively, efficiently, and equitably.

## Objectives

* Understand how dependency ratios are evolving in Washington over the period from 2011 to 2021.
* Determine whether child or aged dependency is driving dependency ratio evolution in the individual counties.
* Explore potential policy implications for those counties with the largest dependency ratios.

## Dependency ratio definitions
3 different dependency ratios will be considered in this analysis: total dependency, child dependency, and elderly dependency. These ratios, as defined by *File & Kominski (2009)* are:

**Total dependency ratio** - the ratio of all dependents to non-dependents.
$$
\frac{\text{child dependents} + \text{elderly dependents}}{\text{non-dependents}}\times 100
$$
**Child dependency ratio** - The ratio of children, aged 0 to 14, in the population to the total number of non-dependents or producers in the population.
$$
\frac{\text{child dependents}}{\text{non-dependents}}\times 100
$$
**elderly dependency ratio** - The ratio of adults, aged 65 and up, in the population to the total number of non-dependents or producers in the population.
$$
\frac{\text{elderly dependents}}{\text{non-dependents}}\times 100
$$
Non-dependents are defined as those individuals in the population, aged 15 to 64, who are available to contribute to the economy, producing good and services and paying taxes.

Dependency ratios approaching 100 are considered problematic as this implies a 1:1 ratio of dependents to those providing the revenue to fund services. There are a number of short comings with this system, as detailed by File & Kominski, but it is still a useful way of analysing population dynamics.

::: {.callout-caution}
## Discrepancies with File & Kominski
File and Kominski have access to data with more granular age slices. As a result, they are able to explore dependency ratios more deeply. The numbers determined in this study will likely be lower than those reported by File & Kominski due to the fact that this study uses 0-14 rather than 0-18 for calculating child dependency ratios.
:::

## Resources
This project provides additional resources including an interactive dashboard and all source code and data used during the project.

* [Dependency ratios dashboard](https://public.tableau.com)
* [Github code repository](https://github.com/TrippBishopStats/total-dependency-ratios-WA)

## Data source
The data used in this project can be found at [County Demographic Dashboard](https://doh.wa.gov/data-and-statistical-reports/washington-tracking-network-wtn/demographics/county-dashboard). All fields were selected and all years 2011-2021 were included.


## References

* [Dependency Rations in the United States: A State and Metropolitan Area Analysis](https://www.census.gov/content/dam/Census/library/working-papers/2012/demo/dependency-ratios-in-the-united-states.pdf)
* [Dependency ratio](https://en.wikipedia.org/wiki/Dependency_ratio)

<section class="button-container">
  <a href="data-prep.html" role="button" class="btn btn-primary">Continue to Data Preparation</a>
</section>